#
# Module manifest for module 'Shortcut.Utilities'
#
# Generated by: Benjamin Cohn
#
# Generated on: 5/3/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\Shortcut.Utilities.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '0327d2d0-b093-4551-8120-f7e2da445c42'

# Author of this module
Author = 'Benjamin Cohn'

# Company or vendor of this module
CompanyName = 'N/A'

# Copyright statement for this module
Copyright = '(c) Benjamin Cohn. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Shortcuts Module'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Open-Shortcut','New-Shortcut','Remove-Shortcut','Get-Shortcut'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'os'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'Shortcut.Utilities.psm1','Shortcut.Utilities.psd1'

}